### PR TITLE
Update browser.ts

### PR DESCRIPTION
**Pull request by netbrain**
Allow for multipart/x-mixed-replace and others.

---

### CODE REVIEW

**Comment by maraisr** [comment]
Havent heard about this one, or others. I dont want to expose myself into inadvertently supporting other mime types I dont have any knowledge about. 

Can you please help me understand the implications of this change? Love to merge this, just with a tiny more clarity!

**Comment by netbrain** [comment]
It's used in many ip cameras.

The general payload looks like this

HTTP/1.1 200 OK
Content-Type: multipart/x-mixed-replace; boundary=myboundary

--myboundary
Content-Type: image/jpeg
Content-length: 12345

[image 1 encoded jpeg data]


--myboundary
Content-Type: image/jpeg
Content-length: 45678

[image 2 encoded jpeg data]

...


In any case, your library should handle all multipart types. Not just one.

**Comment by maraisr** [comment]
Thanks so much for that insight @netbrain. No idea if meros would work with binary data, but doesnt seem entirely out there.

Wondering actually if I should change my api to simply ignore the response header, and assume the developer knows what theyre doing and only calling into meros when they know the response will be a stream. 

Am i blocking you, or can you give me a moment to think about this?

**Comment by artola** [comment]
> Thanks so much for that insight @netbrain. No idea if meros would work with binary data, but doesnt seem entirely out there.
> 
> Wondering actually if I should change my api to simply ignore the response header, and assume the developer knows what theyre doing and only calling into meros when they know the response will be a stream.
> 
> Am i blocking you, or can you give me a moment to think about this?

May be just allow to pass this as option, having the actual value as fallback. Something like `options.contentType ?? 'multipart/mixed'`.

**Comment by maraisr** [comment]
Yeah that is just moving the branch inside meros, when it could be this in user land.

```ts
fetch('..')
   .then(req => {
      if (req.headers['content-type'].includes('multipart/x-mixed-replace')) {
          return meros(req);
      }

      return req.json();
   })
```

all that meros cares about is a `boundary` defined. But yeah, if `multipart/` is a safe prefix that categorically defines the pattern of "parts" however its used (replace or otherwise) — then i see no issue just relaxing the condition inside. Just need to go study this moment in more depth.

@artola does this change impact anything with HC/BCP?

**Comment by artola** [comment]
@maraisr No impact at HC/BCP. We write our network layer, and we will make it work anyway, to keep our users happy ;)

**Comment by maraisr** [comment]
Im going to land this. The `multipart/` prefix is for all things related to the general processing of the content. How the parts are interpreted is up the consumer, and out of scope for meros.

**Pull request merged**
